name: todo_app
description: A new Flutter project.
publish_to: 'none'
version: 1.2.1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.2
  drift: ^2.7.0
  sqlite3_flutter_libs: ^0.5.13
  path_provider: ^2.0.14
  path: ^1.8.2
  flutter_native_splash: ^2.4.1
  shared_preferences: ^2.3.2
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  drift_dev: ^2.7.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/